### PR TITLE
jasmine-p-oss: Upstream to linux kernel v4.4.169

### PR DESCRIPTION
**Pull request by rupansh**
Upstreaming the kernel is important! 
merging upstream allows you to get ahead of Google’s security upstream and has important security as well as performance patches

### CODE REVIEW

**Comment by raphielscape** [comment]
Boi 😂

**Comment by dev-harsh1998** [comment]
😂🤣

**Comment by scafroglia93** [comment]
LOL

**Comment by rupansh** [comment]
@ivan19871002 should be ready to merge

**Comment by twistloop** [comment]
😂😂😂😂

**Comment by yash-garg** [comment]
lol

**Comment by ramabondanp** [comment]
sad react

**Comment by raphielscape** [comment]
F

**Comment by Manish4586** [comment]
F

**Pull request closed without merging**
