### PR TITLE
Oxygen n oss

### PR DESCRIPTION
**Pull request by rajakodumuri**

### CODE REVIEW

**Comment by thananop1987** [comment]
gooodddr

**Comment by Scissordragonboy** [comment]
When till it would be on nougat? You are noob enough or just people wasting their money to buy xiaomi devices?. Xiaomi never update kernel source lmao. Update them or just stop development of xiaomi devices shit.

Noon people trying his best when pro are doing shit for other devices.

**Comment by luk1337** [comment]
ok

**Comment by Scissordragonboy** [comment]
This comment was for xiaomi kernel owners.

**Comment by luk1337** [comment]
ok

**Pull request closed without merging**
